test using examples: drop osbuild and snapd
This test case clones real git repo and checks out specific tag where we
verify that current packit snapshot can create a SRPM. This allowed us
discover potential problems in the past when we touched the SRPM logic.

Nowadays the SRPM process is stable and we have better mechanisms to
discover potential problems when we change this logic:
1. Other tests
2. Sentry
3. Daily validation tests

For this test case, we can't control the specfile and packit.yaml so if
the failure is unrelated we can't do much sadly.

And this is what has happened right now: python packaging changed in
rawhide that osbuild no longer builds:

```
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -sP'
error: Multiple top-level packages discovered in a flat-layout:
['sources', 'SPECPARTS'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or
   `exclude`)
   2. use a `src-layout`
   3. explicitly set `py_modules` or `packages` with a list of names

   To find more information, look for "package discovery" on setuptools
   docs.
   error: Bad exit status from /var/tmp/rpm-tmp.HTwLeq (%build)
       Bad exit status from /var/tmp/rpm-tmp.HTwLeq (%build)
```

I am dropping these two cases as we can't fix them. We could point to a
newer tag but we would still hit this in the future. Let's focus on
validation that we actually can control.

/wall-of-text

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>