Adjust test_iterate_packages_source_git
This should make the test pass also on f39/rawhide.

The problem was with flexmocking the `joinpath` method that I assume
is in the newer Python versions used for the implementation of `/` Path operator
used in multiple places in the code that is run during the tests which made the tests fail on

flexmock.exceptions.MethodSignatureError: Arguments for call joinpath did not match expectations:
E         Received call:	joinpath(".config")